#   ____             __ _
#  / ___|___  _ __  / _(_) __ _
# | |   / _ \| '_ \| |_| |/ _` |
# | |__| (_) | | | |  _| | (_| |
#  \____\___/|_| |_|_| |_|\__, |
#                         |___/
#
# ------------------------------------

# Variables available in ${{var_name}} format
#   These will be replaced with actual values:
#       name:    The name of the theme
#       version: The version of the theme
#       author:  The author of the theme
#       file:    The filename with ext of theme archive

build:
  input_dir: "themes"
  output_dir: "dist"
  archive_name: "${{name}}-${{version}}"

index:
  # Schema version to use
  schema_version: 1.0

  # default repo name
  repo_name: "official"

  # Direct Download link/path for archives
  # MUST add ${{file}} in the filename's place
  download_url: "https://github.com/mydehq/MyThemes/raw/refs/heads/repo/${{file}}"
